Add support for param notifySelf
Servoy/servoy-extensions pull request #4
Opened 2020-09-08 14:15 UTC by jeffreyvdhondel

Add support for param notifySelf

2020-09-08 15:19 UTC, jcompagner requested changes

2020-09-08 15:19 UTC, jcompagner commented on com.servoy.extensions/src/com/servoy/extensions/plugins/rawSQL/RawSQLProvider.java
> +import org.springframework.jdbc.datasource.DataSourceUtils;
why do we suddenly have here a sprintframework import?

2020-09-08 15:19 UTC, jcompagner commented on com.servoy.extensions/src/com/servoy/extensions/plugins/rawSQL/RawSQLProvider.java
> +	public boolean js_notifyDataChange(String serverName, String tableName, IDataSet pksDataset, int action, boolean notifySelf)
we can't change an existing method by just adding a param, then all others calling the old one will be broken.
This should be an additional method where the old once calls the new one with "false"

2020-09-08 15:19 UTC, jcompagner commented on com.servoy.extensions/src/com/servoy/extensions/plugins/rawSQL/RawSQLProvider.java
> +			return getSQLService().notifyDataChange(plugin.getClientPluginAccess().getClientID(), notifySelf ? notifySelf : false, serverMapping.remoteServername,
why "notifySelf ? notifySelf : false," this is already a boolean so this can just be "notifySelf"

2020-09-08 15:19 UTC, jcompagner commented on com.servoy.extensions/src/com/servoy/extensions/plugins/rawSQL/RawSQLProvider.java
how come that all those imports are removed? they should be all used.

2020-09-08 15:34 UTC, p-bakker commented
Isn't Servoy by default already doing the notifySelf since fairly recently?

If I'm correct, the default 'false' isn't correct

2020-09-08 15:55 UTC, jcompagner commented
hmm thats true, we do that because of this case:

https://support.servoy.com/browse/SVY-14318

that added:

https://github.com/Servoy/servoy-extensions/commit/d396af56e0fee550a73b54bea31ebfd21821ae63#diff-467d91df6e0cc47de316c93aec26a088R430

to always also flush locally.

so the default "false" must be because the plugin already flushes its own client, its not needed to call the server and then via via somewhere in the future come back to this client to flush the client itself.

2020-09-08 16:24 UTC, jeffreyvdhondel commented
Thx for the feedback. It tought this switch was that you could broadcast even to your self. It would be very helpful to add this feature.

2020-09-08 16:39 UTC, jcompagner commented
but we already broadcast to our self now all the time.

2020-09-08 16:49 UTC, jeffreyvdhondel commented
Hmmm not what i tested. We have a rabbitmq broadcast set-up. Our delete doesnt broadcast to the prev session. Of the same user.

2020-09-08 17:31 UTC, jcompagner commented
i don't see how we do in that plugin:

	plugin.getClientPluginAccess().getDatabaseManager().notifyDataChange(
				DataSourceUtils.createDBTableDataSource(serverMapping.localServername, tableName), pksDataset, action);

and that is exactly the same call then what would come in when going through the server... (and back to the client)

so you are saying that if you have a ondatabroadcast method 
and you calll notifyDataChange(String serverName, String tableName, IDataSet pksDataset, int action)

where the action is DELETE with a pk of something
it doesn't end up in the databroadcast method?

2020-09-08 17:32 UTC, jcompagner commented
also what is the "prev session" of the same user?

2020-09-08 17:40 UTC, jeffreyvdhondel commented
I dont think it is the delete but. What i understand a change from the broadcast is never from the current client.

I will try to explain what our problem is.

If a use logs in to our system we create a record in our database_table (logged_in_users).
If the same use tries to login they will get a login prompt that they are already logged and if they want to continue that previous session will be logout/terminated. If the user continues we do a delete with the foundset so that we trigger this delete. But there is only a broadcast to the other user from the same organization.

2020-09-08 18:35 UTC, p-bakker commented
Are you keeping a reference to a foundset for table logged_in_users in the (previous) client? If not, your (previous) client might just not get a databroadcast, because it doesn't have any foundsets for that table, thus there's no point in broadcasting

Sidenote: for the mechanism you're building you could also use  application.addClientInfo() and application.getClientCountForInfo(). No need to mess around with records and databroadcasting

2020-09-08 18:41 UTC, jeffreyvdhondel commented
> Are you keeping a reference to a foundset for table logged_in_users in the (previous) client? If not, your (previous) client might just not get a databroadcast, because it doesn't have any foundsets for that table, thus there's no point in broadcasting
> 
> Sidenote: for the mechanism you're building you could also use application.addClientInfo() and application.getClientCountForInfo(). No need to mess around with records and databroadcasting

The user is still connected. So yes there is still a reference to this foundset.

application.addClientInfo() would be a great idea but because we have 2 tomcat instance with rabbitmq we still have to send a broadcast to logout/terminate this user.

2020-09-08 19:08 UTC, jcompagner commented
But those 2 users (same) are in the same tenant right? Then they should get databroarcasts from each other
So I don't get why that wouldn't happen

2020-09-08 19:12 UTC, jeffreyvdhondel commented
There are the same user.

User A logs in create a record. 
(User closes browser)
There is still a session open for this user on the admin page.
User A logs in again get the question if they want to terminate the old session.
fsdelete record on the logged in user.
Now there is no broadcast to the first time the user logs in.
So the result is that there are 2 Users A logged in.

2020-09-08 20:00 UTC, jcompagner commented
then this patch wouldn't help one bit, because that should just work.
if both have a foundset open for that user/session table and have insert something or read something from it
then the other should get databroadcast of that just fine, that is a normal scenario if that doesn't work no databroadcast do work.
as long as the 2 clients have the same tenantid (or none)

2020-09-08 20:29 UTC, jeffreyvdhondel commented
Ok it should work but it doesn't. If i create a logged_in_user record there is no broadcast for the user that created this record(in think this is a good thing).
For an other user with the same tenant there is a broadcast.

Now i want to use the rawsql.notify to send a notify also to myself so that when i do a delete the user gets kicked because there will be a broadcast for this user.

2020-09-08 20:45 UTC, jcompagner commented
"myself" being exactly that same client (not user) ?

So you want to kick your self? Why is that, you can do that right away..

But i have a feeling that you call "myself" also the other same user, that is not "myself" in servoy terms. Users don't matter in this, "clientid" of servoy defines "myself"

i still don't get why there is a different between the 2 clients with the same user that don't databroadcast to each other then 2 clients with different users that do databroadcast, for servoy there is no difference, they are just different clientids

2020-09-08 22:41 UTC, jeffreyvdhondel commented
Yes i meant the already logged in user.

2020-09-09 06:35 UTC, p-bakker commented
@jeffreyvdhondel am not exactly sure what your flow is and what you're expecting, but isn't working. But: are you 100% sure that the client in which you're NOT getting the databroadcast you're expecting is still holding onto a foundset for the table for which you're expecting the databroadcast?

You can check this on the Admin page > Clients > %%theClientToCheck%% and then in the `Tables in use (grouped by server):` section. If the table isn't listed there, you'll never get a databroadcast for it

2020-09-09 06:49 UTC, jeffreyvdhondel commented
@p-bakker I have add the screenshots of the clients that are logged in.
[https://i.ibb.co/0hkR7JM/Screenshot-2020-09-09-at-08-43-01.png](url)
[https://i.ibb.co/wwtzt4T/Screenshot-2020-09-09-at-08-42-53.png](url)

We are logging every databroadcast: 

`		
function autoflexBroadCast(dataSource, action, pks, cached) {
                 var log = new scopes.logging.logging();
		log.createBroadcastLog(dataSource, action, pks);
}
`

2020-09-09 07:57 UTC, jcompagner commented
I just don't get this...

ClientA comes in (userA) that inserts a record
ClientB comes in (userB) that inserts a record. Is this record seen by ClientA?
ClientB logs out. In guess deletes the record, is this seen by ClientA?

Then Client C comes in (userA) for Servoy this is just another client nothing special , that sees that record , asks the user what it wants and then deletes the record. This is then not seen by ClientA? (But clientA did see all things from ClientB?)

That is just weird, you have to be doing something wrong.

Also as an example the 'notifySelf' pararm would only affect clientC it self when clientC calls that notifyDataChange with true. It has nothing to do with Client A, that's for Servoy just a client as any other... There is no link between then because you have the same user..

Does that table where you insert things on have a tenant column? Of so are you sure the clients are not separated because of the tenant value?

2020-09-09 08:26 UTC, jeffreyvdhondel commented
ClientB comes in (userB) that inserts a record. Is this record seen by ClientA? Yes
ClientB logs out. In guess deletes the record, is this seen by ClientA? Yes

This not the problem. The problem is that User A (Client B) logs in again this triggers a fsdelete and Client A doesn't get a broadcast from the delete from client B.

So the "problem" is there is no broadcast to it self.

2020-09-09 08:41 UTC, jcompagner commented
Don't talk about users. Just clients, users are nothing for Servoy that's just for you in your solution..

Talk purely about clients.
Don't use 'self's for users. That doesn't exists. Self is only for clients (so the thing you see on the admin page with a client is) (one webclient, one ngclient)

 I just don't get it if you say the data broadcasts are seen between cliientA an clientB... If they have different users, but if they have the same users they don't.. that's not possible

2020-09-09 08:43 UTC, jeffreyvdhondel commented
> Don't talk about users. Just clients, users are nothing for Servoy that's just for you in your solution..
> 
> Talk purely about clients.
> Don't use 'self's for users. That doesn't exists. Self is only for clients (so the thing you see on the admin page with a client is) (one webclient, one ngclient)
> 
> I just don't get it if you say the data broadcasts are seen between cliientA an clientB... If they have different users, but if they have the same users they don't.. that's not possible

Ok we talk about clients then. It is not possible but i does happen.

2020-09-09 09:13 UTC, jcompagner commented
I just don't get the problem. Without a sample that you see is not working I can't do anything.

Because you say that databroardcasts are working between clients. So I have no idea why that doesn't work in that scenario you talk about.

Again. For Servoy there is no difference between clients based on user.

ClientA with userA
ClientB with userB
ClientC with userA

Should all broadcasts between each other. There is no difference between ClientA <-> ClientB or ClientA <-> ClientC or ClientB <-> ClientC

They are all exactly the same

2020-09-14 16:59 UTC, jeffreyvdhondel commented
> I just don't get the problem. Without a sample that you see is not working I can't do anything.
> 
> Because you say that databroardcasts are working between clients. So I have no idea why that doesn't work in that scenario you talk about.
> 
> Again. For Servoy there is no difference between clients based on user.
> 
> ClientA with userA
> ClientB with userB
> ClientC with userA
> 
> Should all broadcasts between each other. There is no difference between ClientA <-> ClientB or ClientA <-> ClientC or ClientB <-> ClientC
> 
> They are all exactly the same

Thx for the explanation. Found the problem i was debugging the wrong solution.
Thank you for your time.

2020-09-14 16:59 UTC, closed without merging